### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by piegamesde** [miho/MilkGlass#2]
Please add a license to the code so that others might use it in a legal way. You could also try to add this to already existing JavaFX libraries like [ControlsFX](https://bitbucket.org/controlsfx/controlsfx/), that would be nice.

**Comment by miho** [comment]
Legal issues should be resolved now. Have fun with the code :) Adding the code to ControlsFX or JFXtras requires several quality improvements. Currently, I have no plans to do that work. But if you'd like to contribute feel free to create a PR.
